/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#424844",
        "tertiary": "#3a2c21",
        "on-primary-fixed-variant": "#2f4d40",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-dim": "#dbdad5",
        "outline": "#727974",
        "on-tertiary-fixed-variant": "#534437",
        "primary-fixed-dim": "#adcebd",
        "surface-variant": "#e4e2dd",
        "secondary": "#4a6267",
        "error": "#ba1a1a",
        "on-tertiary-container": "#c4af9f",
        "secondary-fixed-dim": "#b1cbd1",
        "inverse-surface": "#30312e",
        "surface-container-highest": "#e4e2dd",
        "on-surface": "#1b1c19",
        "secondary-fixed": "#cde7ed",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#f2f1ec",
        "surface": "#fbf9f4",
        "primary": "#163428",
        "inverse-primary": "#adcebd",
        "on-secondary-container": "#50686d",
        "on-primary": "#ffffff",
        "surface-container": "#f0eee9",
        "secondary-container": "#cde7ed",
        "on-error": "#ffffff",
        "tertiary-fixed": "#f6decd",
        "surface-container-low": "#f5f3ee",
        "on-secondary-fixed": "#051f23",
        "surface-tint": "#466557",
        "on-primary-fixed": "#012116",
        "on-secondary-fixed-variant": "#334b4f",
        "tertiary-fixed-dim": "#d9c2b2",
        "surface-bright": "#fbf9f4",
        "tertiary-container": "#514235",
        "primary-container": "#2d4b3e",
        "surface-container-high": "#eae8e3",
        "outline-variant": "#c1c8c3",
        "on-primary-container": "#99baa9",
        "background": "#fbf9f4",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#25190f",
        "primary-fixed": "#c8ead8",
        "on-background": "#1b1c19",
        "on-secondary": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem", 
        "lg": "0.5rem", 
        "xl": "0.75rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}